project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Jie Zhang"
  site-url: https://tmylla.github.io
  favicon: misc/info/favicon.png
  repo-url: https://github.com/tmylla/tmylla.github.io
  repo-actions: [edit, issue]

  page-footer:
    left: "&copy; Copyright 2026, Jie Zhang"
    right:
      - icon: github
        href: https://github.com/tmylla

  navbar:
    background: "#A9CCE3"
    search: true
    right:
      - text: "Publications"
        href: publications/publications.qmd

      - text: "Blog"
        href: blog/blog.qmd

      - text: "About me"
        href: about_me.qmd

      - text: "Archive"
        menu:
          - text: "Talks"
            href: talks/talks.qmd
          - text: "Projects"
            href: projects/projects.qmd
          - text: "Teaching"
            href: teaching/teaching.qmd


format:
  html:
    theme: styles.scss


